import { GraphData } from '@/types';

export const DEMO_DATA: GraphData = {
  threads: [
    {
      id: 'demo-t1',
      title: 'Produktivität',
      summary: 'Methoden und Werkzeuge um effizienter zu arbeiten und Ziele zu erreichen.',
      status: 'active',
      isPinned: false,
      noteCount: 3,
      noteIds: ['demo-n1', 'demo-n2', 'demo-n3'],
      lastSynthesizedAt: '2026-05-20T10:00:00Z',
      createdAt: '2026-05-01T08:00:00Z',
      updatedAt: '2026-05-20T10:00:00Z',
      xf: 0.35, yf: 0.40,
    },
    {
      id: 'demo-t2',
      title: 'Lernen & Wissen',
      summary: 'Notizen zu Büchern, Kursen und neuen Konzepten die ich verarbeite.',
      status: 'active',
      isPinned: false,
      noteCount: 3,
      noteIds: ['demo-n4', 'demo-n5', 'demo-n6'],
      lastSynthesizedAt: '2026-05-19T14:00:00Z',
      createdAt: '2026-05-02T09:00:00Z',
      updatedAt: '2026-05-19T14:00:00Z',
      xf: 0.65, yf: 0.35,
    },
    {
      id: 'demo-t3',
      title: 'Projektideen',
      summary: 'Ideen für eigene Projekte, Prototypen und kreative Vorhaben.',
      status: 'active',
      isPinned: true,
      noteCount: 2,
      noteIds: ['demo-n7', 'demo-n8'],
      lastSynthesizedAt: null,
      createdAt: '2026-05-10T11:00:00Z',
      updatedAt: '2026-05-22T08:00:00Z',
      xf: 0.50, yf: 0.65,
    },
  ],
  notes: [
    {
      id: 'demo-n1',
      threadId: 'demo-t1',
      title: 'Pomodoro-Technik',
      content: '25 Minuten fokussiert arbeiten, dann 5 Minuten Pause. Nach 4 Runden eine längere Pause von 15–30 Minuten.\n\nFunktioniert gut für tiefe Arbeit.',
      category: 'Lernen',
      createdAt: '2026-05-05T09:00:00Z',
      updatedAt: '2026-05-05T09:00:00Z',
    },
    {
      id: 'demo-n2',
      threadId: 'demo-t1',
      title: 'Deep Work Regeln',
      content: 'Feste Zeiten ohne Ablenkung einplanen. Telefon stumm, Benachrichtigungen aus. Wichtige Aufgaben morgens zuerst.',
      category: 'Arbeit',
      createdAt: '2026-05-08T10:00:00Z',
      updatedAt: '2026-05-08T10:00:00Z',
    },
    {
      id: 'demo-n3',
      threadId: 'demo-t1',
      title: 'Wöchentliches Review',
      content: 'Jeden Sonntag 30 Minuten: Was lief gut? Was nicht? Was sind die Top-3 Ziele für nächste Woche?',
      category: 'Persönlich',
      createdAt: '2026-05-12T11:00:00Z',
      updatedAt: '2026-05-12T11:00:00Z',
    },
    {
      id: 'demo-n4',
      threadId: 'demo-t2',
      title: 'Atomic Habits – Kernthese',
      content: '1% täglich besser werden. Systeme schlagen Ziele. Identitätsbasierte Gewohnheiten formen wer wir sind.',
      category: 'Lernen',
      createdAt: '2026-05-03T14:00:00Z',
      updatedAt: '2026-05-03T14:00:00Z',
    },
    {
      id: 'demo-n5',
      threadId: 'demo-t2',
      title: 'Feynman-Methode',
      content: 'Ein Konzept wirklich verstehen: Es jemandem ohne Vorkenntnisse erklären. Lücken erkennen, nochmal nachschlagen, vereinfachen.',
      category: 'Lernen',
      createdAt: '2026-05-14T16:00:00Z',
      updatedAt: '2026-05-14T16:00:00Z',
    },
    {
      id: 'demo-n6',
      threadId: 'demo-t2',
      title: 'Spaced Repetition',
      content: 'Anki oder ähnliche Tools nutzen. Karten kurz halten. Täglich 10–15 Minuten genügen für dauerhaftes Behalten.',
      category: 'Ideen',
      createdAt: '2026-05-16T09:30:00Z',
      updatedAt: '2026-05-16T09:30:00Z',
    },
    {
      id: 'demo-n7',
      threadId: 'demo-t3',
      title: 'Second Brain App',
      content: 'Eine persönliche Wissensdatenbank mit Graph-Visualisierung. Notizen, Threads, KI-Zusammenfassungen.',
      category: 'Ideen',
      createdAt: '2026-05-10T11:00:00Z',
      updatedAt: '2026-05-10T11:00:00Z',
    },
    {
      id: 'demo-n8',
      threadId: 'demo-t3',
      title: 'Browser-Bookmarklet',
      content: 'Mit einem Klick interessante Seiten und Texte direkt in die Notiz-App speichern. Kein Copy-Paste.',
      category: 'Arbeit',
      createdAt: '2026-05-18T13:00:00Z',
      updatedAt: '2026-05-18T13:00:00Z',
    },
  ],
  similarities: [
    {
      id: 'demo-s1',
      threadId1: 'demo-t1',
      threadId2: 'demo-t2',
      label: 'Selbstoptimierung',
      explanation: 'Beide Threads beschäftigen sich mit persönlichem Wachstum durch Methoden und Wissen.',
    },
    {
      id: 'demo-s2',
      threadId1: 'demo-t2',
      threadId2: 'demo-t3',
      label: 'Wissensmanagement',
      explanation: 'Lerninhalte fließen direkt in Projektideen ein — Theorie trifft Praxis.',
    },
  ],
};
